# Generated by Django 5.0 on 2023-12-21 09:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cntry_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='crncy_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50, unique=True)),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='state_mstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.cntry_mstr')),
            ],
        ),
        migrations.CreateModel(
            name='CmpnyMstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpny_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=20)),
                ('Cmpny_nmbr_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Cmpny_nmbr_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cmpny_mail', models.EmailField(max_length=254, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('gst', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ADMIN_UID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('countries', models.ManyToManyField(to='hrms.cntry_mstr')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.state_mstr')),
            ],
        ),
    ]
