# Generated by Django 5.0 on 2023-12-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_cntry_mstr_crncy_mstr_state_mstr_cmpnymstr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CmpnyMstr',
            new_name='cmpny_mastr',
        ),
    ]
