# Generated by Django 5.0 on 2023-12-22 07:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_rename_cmpny_nmbr_1_cmpny_mastr_company_nmbr_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpny_mastr',
            name='Company_nmbr_2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='emp_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=50)),
                ('emp_last_name', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('emp_date_of_birth', models.DateField()),
                ('emp_personal_email', models.EmailField(max_length=254, unique=True)),
                ('emp_mobile_number_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('emp_mobile_number_2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emp_city', models.CharField(max_length=50)),
                ('emp_permenent_address', models.CharField(max_length=200)),
                ('emp_present_address', models.CharField(max_length=200)),
                ('emp_status', models.BooleanField(default=True)),
                ('emp_hired_date', models.DateField(null=True)),
                ('emp_active_date', models.DateField(blank=True, null=True)),
                ('emp_relegion', models.CharField(max_length=50)),
                ('emp_profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('emp_blood_group', models.CharField(max_length=50)),
                ('emp_nationality', models.CharField()),
                ('emp_marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'divorced')], max_length=1)),
                ('emp_father_name', models.CharField(max_length=50)),
                ('emp_mother_name', models.CharField(max_length=50)),
                ('emp_posting_location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ess', models.BooleanField(default=False)),
                ('epm_ot_applicable', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.brnch_mstr')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.cmpny_mastr')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('ctgry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.ctgry_master')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.dept_master')),
                ('desgntn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.desgntn_master')),
                ('emp_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.emp_master')),
                ('emp_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.cntry_mstr')),
                ('emp_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.state_mstr')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
