# Generated by Django 5.0 on 2023-12-22 07:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_alter_cmpny_mastr_company_nmbr_2_emp_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brnch_mstr',
            name='branch_nmbr_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='cmpny_mastr',
            name='Company_nmbr_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_blood_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_father_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_mobile_number_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_mother_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_nationality',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_posting_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_master',
            name='emp_present_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
