# Generated by Django 5.0 on 2023-12-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_languagemaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_master',
            name='emp_marital_status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Other')], max_length=1),
        ),
    ]
