# Generated by Django 5.0 on 2023-12-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_alter_cmpny_mastr_cmpny_admin_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state_mstr',
            old_name='country_id',
            new_name='country',
        ),
    ]
