# Generated by Django 5.0 on 2023-12-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_alter_state_mstr_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state_mstr',
            old_name='country',
            new_name='country_name',
        ),
    ]
