# Generated by Django 5.0 on 2024-01-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_rename_country_state_mstr_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state_mstr',
            old_name='country_name',
            new_name='country',
        ),
    ]
