# Generated by Django 5.0 on 2024-01-01 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_rename_country_name_state_mstr_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brnch_mstr',
            name='br_countries',
        ),
        migrations.RemoveField(
            model_name='cmpny_mastr',
            name='cmpny_countries',
        ),
        migrations.AddField(
            model_name='brnch_mstr',
            name='br_country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='hrms.cntry_mstr'),
        ),
        migrations.AddField(
            model_name='cmpny_mastr',
            name='cmpny_country',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='hrms.cntry_mstr'),
        ),
        migrations.AlterField(
            model_name='brnch_mstr',
            name='br_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brnch_mstr',
            name='br_state_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='hrms.state_mstr'),
        ),
    ]
