# Generated by Django 5.0 on 2024-01-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_customuser_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpny_mastr',
            name='cmpny_ADMIN_UID',
        ),
        migrations.AlterField(
            model_name='cmpny_mastr',
            name='cmpny_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
