# Generated by Django 5.0 on 2024-01-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_alter_customuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brnch_mstr',
            name='br_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.cmpny_mastr'),
        ),
    ]
