# Generated by Django 5.0 on 2024-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_customusergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, to='hrms.cmpny_mastr'),
        ),
    ]
